apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-reader
  namespace: argo-events
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-reader-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-events-reader
subjects:
  - kind: ServiceAccount
    name: argo-server
    namespace: argo
