apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-workflow-submit-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: payload-from-event
      eventSourceName: my-event-source
      eventName: my-workflow-submit-webhook-event
  triggers:
    - template:
        name: my-submit-workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              # metadata:
              #   generateName: my-parallel-workflow-
              spec:
                synchronization:
                  semaphore:
                    configMapKeyRef:
                      name: my-workflow-config
                      key: workflow
                ttlStrategy:
                  secondsAfterCompletion: 10
                  secondsAfterSuccess: 5
                  secondsAfterFailure: 5
                entrypoint: my-workflow
                # imagePullSecrets:
                #   - name: my-registry-secret
                templates:
                  - name: my-workflow
                    steps:
                      - - name: echo-args-task
                          template: template-echo-args
                      - - name: print-env-task
                          template: template-print-env
                      - - name: ls-task
                          template: template-ls
                      - - name: sleep-task-a
                          template: template-sleep
                        - name: sleep-task-b
                          template: template-sleep
                      - - name: delay-task
                          template: template-delay
                      - - name: sleep-task-c
                          template: template-sleep
                  - name: template-echo-args
                    container:
                      image: alpine
                      command: ["echo"]
                      args: ["Input::\n", ""]
                  - name: template-print-env
                    container:
                      image: alpine
                      command: ["printenv"]
                      env:
                        - name: ENV_ONE
                          value: "true"
                        - name: ENV_TWO
                          value: "false"
                  - name: template-ls
                    container:
                      image: alpine
                      command: [ls]
                      args: ["-l"]
                  - name: template-sleep
                    script:
                      image: alpine
                      command: [sleep]
                      args: ["10"]
                  - name: template-delay
                    suspend:
                      duration: "20s"
          parameters:
            - src:
                dependencyName: payload-from-event
                dataKey: body
              dest: spec.templates.1.container.args.1
            - src:
                dependencyName: payload-from-event
                dataTemplate: "{{ .Input.body.workflow_id | lower }}"
              dest: metadata.name
---
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: my-workflow-terminate-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: terminate-from-event
      eventSourceName: my-event-source
      eventName: my-workflow-terminate-webhook-event
  triggers:
    - template:
        name: my-terminate-workflow
        argoWorkflow:
          operation: terminate
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              # metadata:
              #   name: my-to-be-terminated-workflow
          parameters:
            - src:
                dependencyName: terminate-from-event
                dataTemplate: "{{ .Input.body.workflow_id | lower }}"
              dest: metadata.name
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-workflow-config
data:
  workflow: "3" # Only three workflow can run at given time in particular namespace
  template: "1" # One instances of template can run at a given time in particular namespace
