apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  selector:
    matchLabels:
      app: nest-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: potaesm/nest-app:build-32
          ports:
            - containerPort: 80
