apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  selector:
    matchLabels:
      app: nest-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
        - name: nest-app
          image: potaesm/nest-app:build-264
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 3
